[package]
name = "cargo-ebuild"
version = "0.1.3"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/cardoe/cargo-ebuild"
homepage = "https://github.com/cardoe/cargo-ebuild"
documentation = "https://github.com/cardoe/cargo-ebuild"
readme = "README.md"
keywords = ["cargo-subcommand", "ebuild", "gentoo"]
description = """
Generates an ebuild for a package using the in-tree eclasses.
"""

[dependencies]
cargo = "0.16"
rustc-serialize = "^0.3"
time = "^0.1"
